# NO SHEBANG, require `source` from shell or `INCLUDE` from makefile
#    MUST BE COMPATIBLE WITH BOTH `sh` and `make`
# <@(#)tag:tw.lukas.uberbaud.foo,2025-10-27,22.43.24z/480e8a3>
# vim: ft=ksh ts=4 tw=72 noexpandtab nowrap foldmethod=marker

LLVM_VERSION=21
P=/usr/local/bin

AR=$P/llvm-ar-${LLVM_VERSION}
AS=$P/llvm-as-${LLVM_VERSION}
CC=$P/llvm-clang-${LLVM_VERSION}
CXX=$P/llvm-clang++-${LLVM_VERSION}
CPP=$P/llvm-clang-cpp-${LLVM_VERSION}
LD=$P/llvm-ld.lld-${LLVM_VERSION}
