# <@(#)tag:csongor.greyshirt.net,2017-08-11:tw/03.12.38z/32b357f>
# ksh local profile
# vim: ts=4 ft=ksh

export LSCOLORS=HxfxchahBxEhDhBDBgHcHd
export PRINTER=poco
export ABDUCO_CMD=/bin/ksh

for t in COLLATE CTYPE MESSAGES MONETARY NUMERIC TIME; do
	export LC_$t=en_US.UTF-8
done

osrev=$(uname -r)
osarc=$(uname -m)
PKG_PATH=ftp://ftp4.usa.openbsd.org/pub/OpenBSD/$osrev/packages/$osarc
export PKG_PATH
export TZ=EST5EDT
export PKG_CONFIG_PATH=$XDG_CONFIG_HOME/pkgconfig

p5lib=${xdglocal:-$HOME}/perl5/lib/perl5
[[ -d p5lib ]]&&
	eval "$(env -i perl -I"$p5lib" -Mlocal::lib)"

typeset -fu pre-prompt
export PS1=\
'$(pre-prompt)'\
'\[\e[48;2;108;95;40m'\
'\[\e[33m\]['\
'\[\e[31m\]KSH '\
'\[\e[32m\]\u'\
'\[\e[33m\]@'\
'\[\e[32m\]\h '\
'\[\e[34m\]\W'\
'\[\e[33m\]]'\
'\[\e[48;5;224;31m\]$( local E=$?; ((E))&& printf "[%d]" $E )'\
'\[\e[0m\]\$ '
