#!/bin/ksh
# <@(#)tag:csongor.greyshirt.net,2017-08-08:tw/00.54.34z/37f053f>
# vim: filetype=ksh tabstop=4 textwidth=72 noexpandtab nowrap

set -o nounset;: ${FPATH:?Run from within KSH}

UPPER_LIMIT=20
LOGLEVEL=${LOGLEVEL:-1}
work=${XDG_PUBLICSHARE_DIR:?}/mail
export LOGLEVEL

# Usage {{{1
typeset -- this_pgm=${0##*/}
function usage {
	desparkle "$this_pgm"
	PGM=$REPLY
	sparkle >&2 <<-\
	===SPARKLE===
	^F{4}Usage^f: ^T${PGM}^t ^[^T-n^t^] ^[^T-H^t^]
	         save a mail part to disk and try to open it.
	           ^T-n^t  Do not clean html files.
	           ^T-H^t  Force type to ^Shtml^s.
	       ^T${PGM} -h^t
	         Show this help message.
	===SPARKLE===
	exit 0
} # }}}
# process -options {{{1
function bad_programmer {	# {{{2
	die 'Programmer error:'	\
		"  No getopts action defined for [1m-$1[22m."
  };	# }}}2
forceHTML=false
cleanHtml=true
while getopts ':nhH' Option; do
	case $Option in
		n)	cleanHtml=false;										;;
		H)	forceHTML=true;											;;
		h)	usage;													;;
		\?)	die "Invalid option: [1m-$OPTARG[22m.";				;;
		\:)	die "Option [1m-$OPTARG[22m requires an argument.";	;;
		*)	bad_programmer "$Option";								;;
	esac
done
# remove already processed arguments
shift $((OPTIND-1))
# ready to process non '-' prefixed arguments
# /options }}}1

needs tidy needs-cd needs-path

needs-path -create -or-die "$work"
needs-cd -or-die "$work"
((LOGLEVEL > 1))&& {
	needs sparkle-path
	sparkle-path "$PWD"
	print -r -- "$REPLY" | sparkle
  }

new-array parts

mark=$(mktemp mark-XXXXXXXXX)

if ((LOGLEVEL==0)); then
	mhstore "$@" 2>/dev/null
else
	mhstore "$@"
fi
for f in *; do
	[[ $f == $mark ]]&& continue	# skip mark
	[[ $f -ot $mark ]]&& continue	# skip old files
	if [[ $f == *.txt && $(file -bi "$f") == text/html ]]; then
		H=${f%.*}.html
		mv "$f" "$H" && f=$H
	elif [[ $f == *.html ]]; then
		:
	elif $forceHTML; then
		H=${f%.*}.html
		mv "$f" "$H" && f=$H
	fi
	# fix all the Microsoft (et al.) broken html marked as xhtml
	[[ $f == *.html &&  $cleanHtml == true ]]&&
		clean-html "$f"
	chmod a+r "$f"
	+parts "$f"
done
rm $mark

((${parts[*]+1}))&& open "${parts[@]}"

# Copyright (C) 2017 by Tom Davis <tom@greyshirt.net>.
